title: "seattle.io"
description: "Data, tools, & resources for building Seattle-focused applications"
permalink: /posts/:title
baseurl: ''
exclude: [node_modules, tmp, bin, css, js]

collections:
  contributors:
    output: true
    permalink: /:path/
  resources:
    output: true
    permalink: /resources/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "contributors"
    values:
      layout: "contributor"
